#!/bin/bash

echo -en "\n"

echo "Enter any value"
read value

	if [ $((value%2)) -eq 0 ]
	then
		echo "you entered even number"
 		result=$(( value % 6))
		echo "remainder is $result"
			if [ $result -eq 0 ]
			then
				echo "It is multiple with 6"
			else
				echo "It is not multiple with 6"
					if [ $value -gt 50 ]
					then
						echo "it is greater than 50"
							if [ $value > 100 ]
							then
						#		aa=str($value)
								aa=$( printf '%04d' $$value )
						#		a=len($value)
								a=${#value}
								echo "unit place is {aa[$a - 1]}")
								echo "tens place is {aa[$a - 2]}")
							fi
					else
						echo "it is less than 50"
					fi
			fi
	else
		echo "you entered odd number"
	fi
