#!/bin/bash
set -x
echo
cd /home
for dir in *
do
	chk=$(grep -c "/home/$dir" /etc/passwd)
	if [ $chk -ge 1 ]
	then
		echo "$dir is assigned to a user"
	else
		echo "$dir is not assigned to a user"
	fi
	set +x
done 
